export interface ContractField {
  name: string
  dataType: string
  extent?: number
  required?: boolean
  initial?: string
}

export interface ContractSpec {
  name: string
  tableName?: string
  description?: string
  fields: ContractField[]
}

/**
 * Generate a temp-table include file (.i).
 */
export function generateTempTableInclude(spec: ContractSpec): string {
  const lines: string[] = [
    `/* tt${spec.name}.i — Temp-table definition for ${spec.tableName || spec.name} */`,
    `/* Generated by abl-mcp-core */`,
    '',
    `DEFINE TEMP-TABLE tt${spec.name} NO-UNDO`,
  ]

  if (spec.tableName) {
    lines.push(`  LIKE ${spec.tableName}`)
    lines.push(`  ${spec.fields.map(f => {
      const parts = [`FIELD ${f.name} AS ${f.dataType}${f.extent ? ` EXTENT ${f.extent}` : ''}`]
      if (f.initial) parts.push(`INITIAL ${f.initial}`)
      return `    ${parts.join(' ')}`
    }).join('\n')}`)
    lines.push(`  .`)
  } else {
    for (const f of spec.fields) {
      const parts = [`  FIELD ${f.name} AS ${f.dataType}${f.extent ? ` EXTENT ${f.extent}` : ''}`]
      if (f.initial) parts.push(`INITIAL ${f.initial}`)
      lines.push(parts.join(' '))
    }
  }

  lines.push('  INDEX pk' + spec.name + ' IS PRIMARY UNIQUE.')
  lines.push('  .')
  return lines.join('\n')
}

/**
 * Generate a ProDataSet include file (.i) that wraps the temp-table.
 */
export function generateDataSetInclude(spec: ContractSpec): string {
  return [
    `/* ds${spec.name}.i — ProDataSet definition for ${spec.tableName || spec.name} */`,
    `/* Generated by abl-mcp-core */`,
    '',
    `{ tt${spec.name}.i }`,
    '',
    `DEFINE DATASET ds${spec.name} FOR tt${spec.name}.`,
  ].join('\n')
}

function mapAblToJsonType(ablType: string): string {
  switch (ablType.toUpperCase()) {
    case 'INTEGER':
    case 'INT64': return 'integer'
    case 'DECIMAL':
    case 'FLOAT': return 'number'
    case 'LOGICAL': return 'boolean'
    case 'DATE':
    case 'DATETIME':
    case 'DATETIME-TZ': return 'string'
    default: return 'string'
  }
}

/**
 * Generate JSON Schema from a table/field definition.
 */
export function generateJsonSchema(spec: ContractSpec): string {
  const properties: string[] = []
  const required: string[] = []

  for (const f of spec.fields) {
    properties.push(`    "${f.name}": { "type": "${mapAblToJsonType(f.dataType)}"${f.required ? '' : ', "nullable": true'} }`)
    if (f.required) required.push(`"${f.name}"`)
  }

  const schema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: spec.name,
    description: spec.description || `${spec.name} entity`,
    type: 'object',
    properties: JSON.parse(`{${properties.join(',')}}`),
    ...(required.length ? { required } : {}),
  }

  return JSON.stringify(schema, null, 2)
}

function mapAblToTsType(ablType: string): string {
  switch (ablType.toUpperCase()) {
    case 'CHARACTER':
    case 'LONGCHAR': return 'string'
    case 'INTEGER':
    case 'INT64': return 'number'
    case 'DECIMAL':
    case 'FLOAT':
    case 'DOUBLE': return 'number'
    case 'LOGICAL': return 'boolean'
    case 'DATE':
    case 'DATETIME':
    case 'DATETIME-TZ': return 'string'
    case 'BLOB':
    case 'CLOB':
    case 'MEMPTR': return 'string'
    case 'HANDLE':
    case 'ROWID': return 'string'
    case 'COM-HANDLE': return 'any'
    default: return 'string'
  }
}

export function generateTypeScript(spec: ContractSpec): string {
  const lines: string[] = [
    `/**`,
    ` * ${spec.description || spec.name} interface`,
    ` * Auto-generated from ABL schema`,
    ` */`,
    `export interface ${spec.name} {`,
  ]

  for (const f of spec.fields) {
    const optional = f.required ? '' : '?'
    lines.push(`  ${f.name}${optional}: ${mapAblToTsType(f.dataType)}`)
  }

  lines.push('}')
  return lines.join('\n')
}
